## Panda-DataFrame And Series

Pandas is a powerful data manipulation libraray in Python, widely used for data analysis and data cleaning.It provides two primary data structures. Series and DataFrame. A series is a one - Dimensional array-like object,while a DataFrame is a two - Dimensional , size-mutable,and potentially heterogenous tabular data structure with labeled axes (rows and columns).

In [3]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\totar\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\totar\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\totar\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\totar\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\totar\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\totar\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
import pandas as pd

pandas is 1D array like object that can hold any data type. It is similar to a coloumn in a table.

In [7]:
data=[1,2,3,4,5]
series=pd.Series(data)  ## bada wala S
print("Series \n",series)

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64

create a series from dicitonary

In [8]:
data={'a':1,'b':2,'c':3,'d':4}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
d    4
dtype: int64

In [ ]:
data=[1,2,3,4,5]
index=['a','b','c','d','e']
pd.Series(data,index=index)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [11]:
pd.Series(index,index=data)

1    a
2    b
3    c
4    d
5    e
dtype: object

DataFrame

create a dataframe from a dictionary of list

In [14]:
data={
    'Name':['tarun','utkarsh','amit'],
    'Age':[21,20,22],
    'City':['Banglore','New York','Florida']
}

df=pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age      City
0    tarun   21  Banglore
1  utkarsh   20  New York
2     amit   22   Florida
<class 'pandas.core.frame.DataFrame'>

In [15]:
import numpy as np
np.array(df)

array([['tarun', 21, 'Banglore'],
       ['utkarsh', 20, 'New York'],
       ['amit', 22, 'Florida']], dtype=object)

Create a data frame from a list of dictonaries

In [17]:
data=[
    {'Name':'Tarun','Age':21,'Height':6.2},
    {'Name':'Utkarsh','Age':20,'Height':5.9},
    {'Name':'Amit','Age':22,'Height':5.7}
]
df=pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age  Height
0    Tarun   21     6.2
1  Utkarsh   20     5.9
2     Amit   22     5.7
<class 'pandas.core.frame.DataFrame'>

In [22]:
df=pd.read_csv('ben10_aliens_dataset.csv')
df.head(5)

,name,series,type,species,home_world,power,total_power,combat,speed,durability,intelligence,heat,water,electricity,magic,stealth
0,Heatblast,Original Series,Classic,Pyronite,Pyros,"Pyrokinesis, Fire Absorption, Flight",160,60,49,50,56,100,0,15,0,21
1,Wildmutt,Original Series,Classic,Vulpimancer,Vulpin,"Enhanced Senses, Agility, Sharp Claws",111,75,70,60,30,6,14,14,0,80
2,Diamondhead,Original Series,Classic,Petrosapien,Petropia,"Crystallokinesis, Crystal Constructs, Durability",157,80,48,100,42,20,8,10,1,28
3,XLR8,Original Series,Classic,Kineceleran,Kinet,"Super Speed, Enhanced Reflexes, Friction Manip...",114,70,100,40,57,10,10,8,0,11
4,Grey Matter,Original Series,Classic,Galvan,Galvan Prime,"Enhanced Intelligence, Small Size, Climbing",113,10,40,10,100,13,13,13,5,80

In [23]:
df.tail(5)

,name,series,type,species,home_world,power,total_power,combat,speed,durability,intelligence,heat,water,electricity,magic,stealth
110,Omni-Kix Heatblast,Reboot,Omni-Enhanced/Kix,Enhanced Heatblast,Unknown,"Space Armor, Rocket Flight",156,66,55,55,62,100,0,12,5,25
111,Omni-Kix Cannonbolt,Reboot,Omni-Enhanced/Kix,Enhanced Cannonbolt,Unknown,"Tank Treads, Laser Cannons",167,99,93,100,59,14,16,13,5,22
112,Omni-Kix Humungousaur,Reboot,Omni-Enhanced/Kix,Enhanced Humungousaur,Unknown,"Mecha Armor, shockwave Tail",148,100,44,100,39,9,9,7,3,18
113,Omni-Kix Slapback,Reboot,Omni-Enhanced/Kix,Enhanced Slapback,Unknown,"Heavy Armor, Weight Manipulation",134,40,31,94,47,8,13,13,0,26
114,Omni-Naut Jetray,Reboot,Omni-Enhanced/Kix,Enhanced Jetray,Unknown,"Space Flight, Laser Array",159,37,100,52,38,66,88,5,0,14

Accessing the data from DataFrame

In [25]:
data=[
    {'Name':'Tarun','Age':21,'Height':6.2},
    {'Name':'Utkarsh','Age':20,'Height':5.9},
    {'Name':'Amit','Age':22,'Height':5.7}
]
df=pd.DataFrame(data)
print(df)

      Name  Age  Height
0    Tarun   21     6.2
1  Utkarsh   20     5.9
2     Amit   22     5.7